Update docker-compose to avoid errors
Update docker-compose.

This fix the following:

~~~
jbono@MacBook [~/sleepy-puppy-docker]> docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
sleepy-puppy-web.environment.DEBUG contains false, which is an invalid type, it should be a string, number, or a null
~~~